import type { LayoutTheme } from './types';

/**
 * 22 layout moods. Layout themes reshape the library, the reader and the
 * shell itself — container width, rhythm, card proportions and how the
 * collection is composed on screen.
 */
export const LAYOUT_THEMES: LayoutTheme[] = [
  {
    id: 'atlas',
    name: 'Atlas',
    note: 'Balanced responsive grid. Reliable at every size.',
    mode: 'grid',
    container: '1280px',
    gap: '20px',
    radius: '18px',
    cardMin: '280px',
    cardPad: '20px',
    sidebar: '248px',
    measure: '68ch',
    rhythm: '28px',
  },
  {
    id: 'bento',
    name: 'Bento Box',
    note: 'Mixed tile sizes, like a well-packed lunchbox of ideas.',
    mode: 'bento',
    container: '1320px',
    gap: '18px',
    radius: '22px',
    cardMin: '240px',
    cardPad: '20px',
    sidebar: '248px',
    measure: '70ch',
    rhythm: '26px',
  },
  {
    id: 'masonry',
    name: 'Masonry Wall',
    note: 'Columns of varying heights — perfect for browsing by feel.',
    mode: 'masonry',
    container: '1360px',
    gap: '18px',
    radius: '16px',
    cardMin: '260px',
    cardPad: '20px',
    sidebar: '240px',
    measure: '66ch',
    rhythm: '24px',
  },
  {
    id: 'timeline',
    name: 'Timeline',
    note: 'Every speech pinned to a rail by date. Chronological thinking.',
    mode: 'timeline',
    container: '1080px',
    gap: '18px',
    radius: '16px',
    cardMin: '420px',
    cardPad: '20px',
    sidebar: '240px',
    measure: '66ch',
    rhythm: '22px',
  },
  {
    id: 'spotlight',
    name: 'Spotlight',
    note: 'One feature speech on stage, the rest queued below.',
    mode: 'spotlight',
    container: '1180px',
    gap: '20px',
    radius: '20px',
    cardMin: '520px',
    cardPad: '26px',
    sidebar: '240px',
    measure: '68ch',
    rhythm: '30px',
  },
  {
    id: 'gallery',
    name: 'Gallery',
    note: 'Uniform square tiles. Visual, calm, poster-like.',
    mode: 'gallery',
    container: '1300px',
    gap: '16px',
    radius: '14px',
    cardMin: '220px',
    cardPad: '18px',
    sidebar: '232px',
    measure: '64ch',
    rhythm: '24px',
  },
  {
    id: 'list',
    name: 'Compact List',
    note: 'Dense rows. Scan a hundred titles without scrolling far.',
    mode: 'list',
    container: '1020px',
    gap: '8px',
    radius: '12px',
    cardMin: '100%',
    cardPad: '14px',
    sidebar: '232px',
    measure: '70ch',
    rhythm: '18px',
  },
  {
    id: 'split',
    name: 'Split View',
    note: 'List on the left, live preview on the right. Inbox energy.',
    mode: 'split',
    container: '1400px',
    gap: '14px',
    radius: '14px',
    cardMin: '320px',
    cardPad: '16px',
    sidebar: '240px',
    measure: '62ch',
    rhythm: '20px',
  },
  {
    id: 'editorial',
    name: 'Editorial',
    note: 'Two text columns with drop caps, like a Sunday magazine.',
    mode: 'editorial',
    container: '1240px',
    gap: '24px',
    radius: '10px',
    cardMin: '340px',
    cardPad: '24px',
    sidebar: '252px',
    measure: '60ch',
    rhythm: '32px',
  },
  {
    id: 'carousel',
    name: 'Carousel',
    note: 'Horizontal snap-scrolling rail. Thumb-friendly on phones.',
    mode: 'carousel',
    container: '1440px',
    gap: '18px',
    radius: '20px',
    cardMin: '300px',
    cardPad: '22px',
    sidebar: '240px',
    measure: '66ch',
    rhythm: '24px',
  },
  {
    id: 'zen',
    name: 'Zen',
    note: 'One narrow column, nothing else. Pure concentration.',
    mode: 'zen',
    container: '820px',
    gap: '22px',
    radius: '16px',
    cardMin: '100%',
    cardPad: '22px',
    sidebar: '224px',
    measure: '58ch',
    rhythm: '34px',
  },
  {
    id: 'dashboard',
    name: 'Dashboard',
    note: 'Dense panels of stats and shortcuts. For power users.',
    mode: 'dashboard',
    container: '1440px',
    gap: '16px',
    radius: '14px',
    cardMin: '220px',
    cardPad: '16px',
    sidebar: '256px',
    measure: '72ch',
    rhythm: '20px',
  },
  {
    id: 'dossier',
    name: 'Dossier',
    note: 'Document-style sheets with tabs and reference numbers.',
    mode: 'dossier',
    container: '1100px',
    gap: '12px',
    radius: '8px',
    cardMin: '100%',
    cardPad: '18px',
    sidebar: '248px',
    measure: '68ch',
    rhythm: '18px',
  },
  {
    id: 'newsprint',
    name: 'Newsprint',
    note: 'Multi-column broadsheet with rules and bylines.',
    mode: 'newsprint',
    container: '1320px',
    gap: '22px',
    radius: '6px',
    cardMin: '300px',
    cardPad: '18px',
    sidebar: '248px',
    measure: '62ch',
    rhythm: '26px',
  },
  {
    id: 'showcase',
    name: 'Showcase',
    note: 'Big poster cards with roomy covers and long previews.',
    mode: 'showcase',
    container: '1220px',
    gap: '26px',
    radius: '24px',
    cardMin: '420px',
    cardPad: '28px',
    sidebar: '240px',
    measure: '70ch',
    rhythm: '34px',
  },
  {
    id: 'ribbon',
    name: 'Ribbon',
    note: 'Full-bleed horizontal bands stacked down the page.',
    mode: 'ribbon',
    container: '100%',
    gap: '14px',
    radius: '18px',
    cardMin: '100%',
    cardPad: '22px',
    sidebar: '236px',
    measure: '68ch',
    rhythm: '22px',
  },
  {
    id: 'table',
    name: 'Index Table',
    note: 'Sortable rows of metadata. Spreadsheet people, rejoice.',
    mode: 'table',
    container: '1360px',
    gap: '4px',
    radius: '8px',
    cardMin: '100%',
    cardPad: '12px',
    sidebar: '240px',
    measure: '74ch',
    rhythm: '16px',
  },
  {
    id: 'constellation',
    name: 'Constellation',
    note: 'Varied tile sizes arranged organically. Designed chaos.',
    mode: 'constellation',
    container: '1340px',
    gap: '20px',
    radius: '20px',
    cardMin: '200px',
    cardPad: '20px',
    sidebar: '240px',
    measure: '66ch',
    rhythm: '26px',
  },
  {
    id: 'theatre',
    name: 'Theatre',
    note: 'Widescreen 16:9 cover cards, like a streaming shelf.',
    mode: 'theatre',
    container: '1380px',
    gap: '20px',
    radius: '18px',
    cardMin: '340px',
    cardPad: '0px',
    sidebar: '240px',
    measure: '68ch',
    rhythm: '28px',
  },
  {
    id: 'focus',
    name: 'Focus',
    note: 'One speech at a time, filling the viewport. No escape.',
    mode: 'focus',
    container: '900px',
    gap: '20px',
    radius: '22px',
    cardMin: '100%',
    cardPad: '30px',
    sidebar: '224px',
    measure: '56ch',
    rhythm: '30px',
  },
  {
    id: 'stack',
    name: 'Card Stack',
    note: 'Overlapping deck of cards — flick through the pile.',
    mode: 'stack',
    container: '1040px',
    gap: '18px',
    radius: '20px',
    cardMin: '100%',
    cardPad: '24px',
    sidebar: '236px',
    measure: '64ch',
    rhythm: '24px',
  },
  {
    id: 'ledger',
    name: 'Ledger',
    note: 'Minimal ruled rows with a hairline grid. Accountant chic.',
    mode: 'ledger',
    container: '1180px',
    gap: '0px',
    radius: '4px',
    cardMin: '100%',
    cardPad: '16px',
    sidebar: '248px',
    measure: '70ch',
    rhythm: '14px',
  },
];

export const DEFAULT_LAYOUT = 'atlas';
