import type { LayoutTheme } from './types';

/**
 * 22 ways to arrange a shelf. Named after the objects people actually keep
 * papers in — reading rooms, card catalogues, notice boards, scrapbooks —
 * rather than after CSS properties.
 */
export const LAYOUT_THEMES: LayoutTheme[] = [
  {
    id: 'reading-room',
    name: 'Reading Room',
    note: 'A balanced shelf of cards. Reliable at every size, the house default.',
    mode: 'grid',
    container: '1260px',
    gap: '20px',
    radius: '10px',
    cardMin: '286px',
    cardPad: '20px',
    sidebar: '248px',
    measure: '68ch',
    rhythm: '28px',
  },
  {
    id: 'card-catalogue',
    name: 'Card Catalogue',
    note: 'Dense ruled rows, exactly like a library drawer.',
    mode: 'list',
    container: '1040px',
    gap: '8px',
    radius: '6px',
    cardMin: '100%',
    cardPad: '14px',
    sidebar: '240px',
    measure: '70ch',
    rhythm: '18px',
  },
  {
    id: 'notice-board',
    name: 'Notice Board',
    note: 'Mixed tile sizes pinned up any which way, but tidily.',
    mode: 'bento',
    container: '1300px',
    gap: '18px',
    radius: '10px',
    cardMin: '240px',
    cardPad: '20px',
    sidebar: '248px',
    measure: '70ch',
    rhythm: '26px',
  },
  {
    id: 'broadside',
    name: 'Broadside',
    note: 'Big poster sheets with room to say something.',
    mode: 'showcase',
    container: '1200px',
    gap: '26px',
    radius: '12px',
    cardMin: '420px',
    cardPad: '28px',
    sidebar: '240px',
    measure: '70ch',
    rhythm: '34px',
  },
  {
    id: 'chapbook',
    name: 'Chapbook',
    note: 'One narrow column, nothing else. A pamphlet in your hands.',
    mode: 'zen',
    container: '820px',
    gap: '22px',
    radius: '10px',
    cardMin: '100%',
    cardPad: '22px',
    sidebar: '224px',
    measure: '58ch',
    rhythm: '34px',
  },
  {
    id: 'leaflet',
    name: 'Leaflet',
    note: 'Uniform square tiles, folded and stacked.',
    mode: 'gallery',
    container: '1280px',
    gap: '16px',
    radius: '8px',
    cardMin: '224px',
    cardPad: '18px',
    sidebar: '232px',
    measure: '64ch',
    rhythm: '24px',
  },
  {
    id: 'almanac',
    name: 'Almanac',
    note: 'Every entry pinned to a rail by its date.',
    mode: 'timeline',
    container: '1060px',
    gap: '18px',
    radius: '10px',
    cardMin: '420px',
    cardPad: '20px',
    sidebar: '240px',
    measure: '66ch',
    rhythm: '22px',
  },
  {
    id: 'scrapbook',
    name: 'Scrapbook',
    note: 'Columns of uneven heights, pasted in where they fit.',
    mode: 'masonry',
    container: '1340px',
    gap: '18px',
    radius: '10px',
    cardMin: '262px',
    cardPad: '20px',
    sidebar: '240px',
    measure: '66ch',
    rhythm: '24px',
  },
  {
    id: 'ledger',
    name: 'Ledger',
    note: 'Hairline-ruled entries, no ornament at all.',
    mode: 'ledger',
    container: '1160px',
    gap: '0px',
    radius: '3px',
    cardMin: '100%',
    cardPad: '16px',
    sidebar: '248px',
    measure: '70ch',
    rhythm: '14px',
  },
  {
    id: 'index-cards',
    name: 'Index Cards',
    note: 'Sortable rows of metadata. For people who like a table.',
    mode: 'table',
    container: '1340px',
    gap: '4px',
    radius: '6px',
    cardMin: '100%',
    cardPad: '12px',
    sidebar: '240px',
    measure: '74ch',
    rhythm: '16px',
  },
  {
    id: 'gallery-wall',
    name: 'Gallery Wall',
    note: 'Varied frames hung in a pleasing, slightly uneven arrangement.',
    mode: 'constellation',
    container: '1320px',
    gap: '20px',
    radius: '10px',
    cardMin: '200px',
    cardPad: '20px',
    sidebar: '240px',
    measure: '66ch',
    rhythm: '26px',
  },
  {
    id: 'bulletin',
    name: 'Bulletin',
    note: 'Full-bleed bands stacked down the page, like notices.',
    mode: 'ribbon',
    container: '100%',
    gap: '14px',
    radius: '10px',
    cardMin: '100%',
    cardPad: '22px',
    sidebar: '236px',
    measure: '68ch',
    rhythm: '22px',
  },
  {
    id: 'news-sheet',
    name: 'News Sheet',
    note: 'Multi-column broadsheet with rules between the columns.',
    mode: 'newsprint',
    container: '1300px',
    gap: '22px',
    radius: '4px',
    cardMin: '300px',
    cardPad: '18px',
    sidebar: '248px',
    measure: '62ch',
    rhythm: '26px',
  },
  {
    id: 'columns',
    name: 'Two Columns',
    note: 'Editorial columns with drop caps where the text begins.',
    mode: 'editorial',
    container: '1220px',
    gap: '24px',
    radius: '6px',
    cardMin: '340px',
    cardPad: '24px',
    sidebar: '252px',
    measure: '60ch',
    rhythm: '32px',
  },
  {
    id: 'desk',
    name: 'Desk',
    note: 'List on the left, the open page on the right.',
    mode: 'split',
    container: '1380px',
    gap: '14px',
    radius: '8px',
    cardMin: '320px',
    cardPad: '16px',
    sidebar: '240px',
    measure: '62ch',
    rhythm: '20px',
  },
  {
    id: 'rail',
    name: 'Rail',
    note: 'A horizontal shelf you push along with your thumb.',
    mode: 'carousel',
    container: '1420px',
    gap: '18px',
    radius: '10px',
    cardMin: '300px',
    cardPad: '22px',
    sidebar: '240px',
    measure: '66ch',
    rhythm: '24px',
  },
  {
    id: 'stage',
    name: 'Stage',
    note: 'One feature piece on the boards, the rest queued below.',
    mode: 'spotlight',
    container: '1160px',
    gap: '20px',
    radius: '12px',
    cardMin: '520px',
    cardPad: '26px',
    sidebar: '240px',
    measure: '68ch',
    rhythm: '30px',
  },
  {
    id: 'slideshow',
    name: 'Slideshow',
    note: 'One at a time, filling the view. No escape, no scrolling.',
    mode: 'focus',
    container: '900px',
    gap: '20px',
    radius: '12px',
    cardMin: '100%',
    cardPad: '30px',
    sidebar: '224px',
    measure: '56ch',
    rhythm: '30px',
  },
  {
    id: 'stack-of-pages',
    name: 'Stack of Pages',
    note: 'Sheets piled on a desk, edges showing, top one readable.',
    mode: 'stack',
    container: '1020px',
    gap: '18px',
    radius: '10px',
    cardMin: '100%',
    cardPad: '24px',
    sidebar: '236px',
    measure: '64ch',
    rhythm: '24px',
  },
  {
    id: 'display-case',
    name: 'Display Case',
    note: 'Widescreen covers behind glass, like a museum vitrine.',
    mode: 'theatre',
    container: '1360px',
    gap: '20px',
    radius: '10px',
    cardMin: '340px',
    cardPad: '0px',
    sidebar: '240px',
    measure: '68ch',
    rhythm: '28px',
  },
  {
    id: 'workbench',
    name: 'Workbench',
    note: 'Dense panels of numbers and shortcuts for the organised.',
    mode: 'dashboard',
    container: '1420px',
    gap: '14px',
    radius: '8px',
    cardMin: '220px',
    cardPad: '16px',
    sidebar: '256px',
    measure: '72ch',
    rhythm: '20px',
  },
  {
    id: 'folder',
    name: 'Folder',
    note: 'Document sheets with tabs, filed in order.',
    mode: 'dossier',
    container: '1100px',
    gap: '12px',
    radius: '5px',
    cardMin: '100%',
    cardPad: '18px',
    sidebar: '248px',
    measure: '68ch',
    rhythm: '18px',
  },
];

export const DEFAULT_LAYOUT = 'reading-room';
