import type { MotionTheme } from './types';

/**
 * 22 motion personalities, named the way a person moves rather than the way a
 * library names an easing curve. "Still" genuinely freezes the interface;
 * "Breath" is slow enough to sync with your own.
 */
export const MOTION_THEMES: MotionTheme[] = [
  {
    id: 'still',
    name: 'Still',
    note: 'Nothing moves. The safest choice for vestibular sensitivity.',
    enter: 'pb-fade',
    ease: 'linear',
    easeSpring: 'linear',
    fast: '1ms',
    base: '1ms',
    slow: '1ms',
    stagger: 0,
    lift: '0px',
    scale: '1',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '0s',
    speed: 0,
  },
  {
    id: 'steady',
    name: 'Steady',
    note: 'The house timing. Arrives, settles, gets out of the way.',
    enter: 'pb-rise',
    ease: 'cubic-bezier(0.24,0.6,0.32,1)',
    easeSpring: 'cubic-bezier(0.32,1.12,0.58,1)',
    fast: '140ms',
    base: '300ms',
    slow: '560ms',
    stagger: 34,
    lift: '2px',
    scale: '1.004',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '20s',
    speed: 1,
  },
  {
    id: 'unhurried',
    name: 'Unhurried',
    note: 'Long, low-gear easing. Nothing here is in a hurry.',
    enter: 'pb-glide',
    ease: 'cubic-bezier(0.18,0.82,0.28,1)',
    easeSpring: 'cubic-bezier(0.18,0.9,0.3,1)',
    fast: '200ms',
    base: '460ms',
    slow: '820ms',
    stagger: 52,
    lift: '3px',
    scale: '1.008',
    blur: '0px',
    ambient: 'drift',
    ambientSpeed: '30s',
    speed: 1.2,
  },
  {
    id: 'by-hand',
    name: 'By Hand',
    note: 'Slight overshoot, like a pen finishing a stroke.',
    enter: 'pb-pop',
    ease: 'cubic-bezier(0.3,1.2,0.5,1)',
    easeSpring: 'cubic-bezier(0.34,1.35,0.6,1)',
    fast: '160ms',
    base: '340ms',
    slow: '620ms',
    stagger: 40,
    lift: '4px',
    scale: '1.012',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '16s',
    speed: 1,
  },
  {
    id: 'page-turn',
    name: 'Page Turn',
    note: 'Content swings in from the side, the way a leaf turns.',
    enter: 'pb-slide-left',
    ease: 'cubic-bezier(0.2,0.85,0.3,1)',
    easeSpring: 'cubic-bezier(0.2,1,0.3,1)',
    fast: '180ms',
    base: '380ms',
    slow: '660ms',
    stagger: 46,
    lift: '2px',
    scale: '1',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '18s',
    speed: 1.05,
  },
  {
    id: 'settle',
    name: 'Settle',
    note: 'Drops into place and stops dead. Like a stamp.',
    enter: 'pb-drop',
    ease: 'cubic-bezier(0.4,1.1,0.5,1)',
    easeSpring: 'cubic-bezier(0.4,1.3,0.5,1)',
    fast: '150ms',
    base: '320ms',
    slow: '580ms',
    stagger: 36,
    lift: '3px',
    scale: '1.006',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '14s',
    speed: 0.95,
  },
  {
    id: 'quickstep',
    name: 'Quickstep',
    note: 'Short and decisive, for people who click faster than the page.',
    enter: 'pb-slide-up',
    ease: 'cubic-bezier(0.2,0,0,1)',
    easeSpring: 'cubic-bezier(0.2,0,0,1)',
    fast: '90ms',
    base: '180ms',
    slow: '320ms',
    stagger: 16,
    lift: '2px',
    scale: '1.003',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '12s',
    speed: 0.65,
  },
  {
    id: 'skip',
    name: 'Skip',
    note: 'A small hop on arrival. Hard to stay grumpy at.',
    enter: 'pb-drop',
    ease: 'cubic-bezier(0.42,1.4,0.5,1)',
    easeSpring: 'cubic-bezier(0.42,1.6,0.5,1)',
    fast: '170ms',
    base: '360ms',
    slow: '620ms',
    stagger: 44,
    lift: '6px',
    scale: '1.02',
    blur: '0px',
    ambient: 'pulse',
    ambientSpeed: '9s',
    speed: 1.05,
  },
  {
    id: 'breath',
    name: 'Breath',
    note: 'Slow ambient swell. Designed to be breathed along with.',
    enter: 'pb-fade',
    ease: 'cubic-bezier(0.4,0,0.5,1)',
    easeSpring: 'cubic-bezier(0.4,0,0.5,1)',
    fast: '260ms',
    base: '620ms',
    slow: '1100ms',
    stagger: 70,
    lift: '2px',
    scale: '1.005',
    blur: '0px',
    ambient: 'pulse',
    ambientSpeed: '8s',
    speed: 1.35,
  },
  {
    id: 'drift',
    name: 'Drift',
    note: 'Everything floats upward like dust in a window.',
    enter: 'pb-rise',
    ease: 'cubic-bezier(0.33,0.85,0.45,1)',
    easeSpring: 'cubic-bezier(0.33,1,0.45,1)',
    fast: '220ms',
    base: '480ms',
    slow: '900ms',
    stagger: 62,
    lift: '3px',
    scale: '1.005',
    blur: '1px',
    ambient: 'drift',
    ambientSpeed: '24s',
    speed: 1.2,
  },
  {
    id: 'tap',
    name: 'Tap',
    note: 'Micro-feedback only. Interface answers, never performs.',
    enter: 'pb-fade',
    ease: 'cubic-bezier(0.3,0,0.2,1)',
    easeSpring: 'cubic-bezier(0.3,0,0.2,1)',
    fast: '80ms',
    base: '160ms',
    slow: '280ms',
    stagger: 14,
    lift: '1px',
    scale: '1.002',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '10s',
    speed: 0.6,
  },
  {
    id: 'nod',
    name: 'Nod',
    note: 'A small downward acknowledgement on arrival.',
    enter: 'pb-swing',
    ease: 'cubic-bezier(0.4,0.9,0.4,1)',
    easeSpring: 'cubic-bezier(0.4,1.05,0.4,1)',
    fast: '150ms',
    base: '300ms',
    slow: '540ms',
    stagger: 32,
    lift: '2px',
    scale: '1.004',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '16s',
    speed: 0.95,
  },
  {
    id: 'wave',
    name: 'Wave',
    note: 'Big per-item stagger — a list arrives like a hand across a page.',
    enter: 'pb-rise',
    ease: 'cubic-bezier(0.24,0.9,0.32,1)',
    easeSpring: 'cubic-bezier(0.24,1.05,0.32,1)',
    fast: '160ms',
    base: '340ms',
    slow: '620ms',
    stagger: 100,
    lift: '3px',
    scale: '1.006',
    blur: '0px',
    ambient: 'float',
    ambientSpeed: '18s',
    speed: 1.1,
  },
  {
    id: 'unfold',
    name: 'Unfold',
    note: 'Panels open like a letter being flattened on a table.',
    enter: 'pb-unfold',
    ease: 'cubic-bezier(0.28,1.1,0.4,1)',
    easeSpring: 'cubic-bezier(0.28,1.2,0.4,1)',
    fast: '190ms',
    base: '420ms',
    slow: '720ms',
    stagger: 48,
    lift: '3px',
    scale: '1.008',
    blur: '1px',
    ambient: 'none',
    ambientSpeed: '20s',
    speed: 1.1,
  },
  {
    id: 'ink-bleed',
    name: 'Ink Bleed',
    note: 'Content resolves out of a soft blur, like ink finding paper.',
    enter: 'pb-blur-in',
    ease: 'cubic-bezier(0.2,0.9,0.3,1)',
    easeSpring: 'cubic-bezier(0.2,0.95,0.3,1)',
    fast: '220ms',
    base: '480ms',
    slow: '820ms',
    stagger: 50,
    lift: '2px',
    scale: '1.008',
    blur: '8px',
    ambient: 'shimmer',
    ambientSpeed: '18s',
    speed: 1.25,
  },
  {
    id: 'fold',
    name: 'Fold',
    note: 'Cards tip forward as they arrive, like a leaflet opening.',
    enter: 'pb-flip-in',
    ease: 'cubic-bezier(0.3,1.05,0.4,1)',
    easeSpring: 'cubic-bezier(0.3,1.15,0.4,1)',
    fast: '180ms',
    base: '400ms',
    slow: '700ms',
    stagger: 44,
    lift: '4px',
    scale: '1.01',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '18s',
    speed: 1.1,
  },
  {
    id: 'step',
    name: 'Step',
    note: 'Measured, mechanical, one beat at a time.',
    enter: 'pb-type',
    ease: 'steps(24,end)',
    easeSpring: 'cubic-bezier(0.3,0.8,0.4,1)',
    fast: '180ms',
    base: '400ms',
    slow: '680ms',
    stagger: 58,
    lift: '1px',
    scale: '1',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '20s',
    speed: 1,
  },
  {
    id: 'glide',
    name: 'Glide',
    note: 'Long tail-out easing. Everything feels considered.',
    enter: 'pb-glide',
    ease: 'cubic-bezier(0.16,1,0.3,1)',
    easeSpring: 'cubic-bezier(0.16,1,0.3,1)',
    fast: '200ms',
    base: '520ms',
    slow: '1000ms',
    stagger: 60,
    lift: '4px',
    scale: '1.01',
    blur: '0px',
    ambient: 'float',
    ambientSpeed: '22s',
    speed: 1.3,
  },
  {
    id: 'hush',
    name: 'Hush',
    note: 'Barely-there fades. Present but never insisting on attention.',
    enter: 'pb-fade',
    ease: 'cubic-bezier(0.4,0,0.4,1)',
    easeSpring: 'cubic-bezier(0.4,0,0.4,1)',
    fast: '160ms',
    base: '340ms',
    slow: '620ms',
    stagger: 28,
    lift: '1px',
    scale: '1.002',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '24s',
    speed: 0.9,
  },
  {
    id: 'lantern',
    name: 'Lantern',
    note: 'A gentle background glow breathes while the page stays calm.',
    enter: 'pb-rise',
    ease: 'cubic-bezier(0.28,0.8,0.36,1)',
    easeSpring: 'cubic-bezier(0.28,1,0.36,1)',
    fast: '170ms',
    base: '360ms',
    slow: '640ms',
    stagger: 38,
    lift: '3px',
    scale: '1.006',
    blur: '0px',
    ambient: 'pulse',
    ambientSpeed: '6s',
    speed: 1.05,
  },
  {
    id: 'march',
    name: 'March',
    note: 'Snappy, even timing. Good for rehearsing to a beat.',
    enter: 'pb-slide-up',
    ease: 'cubic-bezier(0,0,0.2,1)',
    easeSpring: 'cubic-bezier(0,0,0.2,1)',
    fast: '70ms',
    base: '150ms',
    slow: '260ms',
    stagger: 12,
    lift: '2px',
    scale: '1.004',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '10s',
    speed: 0.55,
  },
  {
    id: 'tide',
    name: 'Tide',
    note: 'Slow orbit in the background; the text itself never moves.',
    enter: 'pb-fade',
    ease: 'cubic-bezier(0.35,0.7,0.4,1)',
    easeSpring: 'cubic-bezier(0.35,0.9,0.4,1)',
    fast: '200ms',
    base: '420ms',
    slow: '780ms',
    stagger: 44,
    lift: '2px',
    scale: '1.004',
    blur: '0px',
    ambient: 'orbit',
    ambientSpeed: '34s',
    speed: 1.15,
  },
];

export const DEFAULT_MOTION = 'steady';
