import type { MotionTheme } from './types';

/**
 * 22 motion personalities. `speed` is a global multiplier applied on top of
 * `prefers-reduced-motion`, so "Still" genuinely freezes the interface while
 * "Cascade" turns every list into a wave.
 */
export const MOTION_THEMES: MotionTheme[] = [
  {
    id: 'still',
    name: 'Still',
    note: 'No animation at all. The safest choice for vestibular sensitivity.',
    enter: 'pb-fade',
    ease: 'linear',
    easeSpring: 'linear',
    fast: '1ms',
    base: '1ms',
    slow: '1ms',
    stagger: 0,
    lift: '0px',
    scale: '1',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '0s',
    speed: 0,
  },
  {
    id: 'calm',
    name: 'Calm',
    note: 'Barely-there fades. Present but never insistent.',
    enter: 'pb-fade',
    ease: 'cubic-bezier(0.4,0,0.2,1)',
    easeSpring: 'cubic-bezier(0.4,0,0.2,1)',
    fast: '120ms',
    base: '260ms',
    slow: '520ms',
    stagger: 24,
    lift: '1px',
    scale: '1.002',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '26s',
    speed: 0.7,
  },
  {
    id: 'breeze',
    name: 'Breeze',
    note: 'Light lifts and soft landings. The everyday default.',
    enter: 'pb-rise',
    ease: 'cubic-bezier(0.22,0.61,0.36,1)',
    easeSpring: 'cubic-bezier(0.34,1.3,0.64,1)',
    fast: '140ms',
    base: '280ms',
    slow: '600ms',
    stagger: 40,
    lift: '3px',
    scale: '1.008',
    blur: '0px',
    ambient: 'float',
    ambientSpeed: '18s',
    speed: 1,
  },
  {
    id: 'glide',
    name: 'Glide',
    note: 'Long, luxurious easing — everything feels expensive.',
    enter: 'pb-glide',
    ease: 'cubic-bezier(0.16,1,0.3,1)',
    easeSpring: 'cubic-bezier(0.16,1,0.3,1)',
    fast: '200ms',
    base: '480ms',
    slow: '900ms',
    stagger: 60,
    lift: '4px',
    scale: '1.01',
    blur: '0px',
    ambient: 'drift',
    ambientSpeed: '24s',
    speed: 1.15,
  },
  {
    id: 'spring',
    name: 'Spring',
    note: 'Overshooting springs with a playful landing.',
    enter: 'pb-pop',
    ease: 'cubic-bezier(0.34,1.56,0.64,1)',
    easeSpring: 'cubic-bezier(0.34,1.56,0.64,1)',
    fast: '160ms',
    base: '360ms',
    slow: '620ms',
    stagger: 45,
    lift: '6px',
    scale: '1.03',
    blur: '0px',
    ambient: 'float',
    ambientSpeed: '14s',
    speed: 1,
  },
  {
    id: 'elastic',
    name: 'Elastic',
    note: 'Extra bounce. Great on touch devices, cheeky on desktop.',
    enter: 'pb-swing',
    ease: 'cubic-bezier(0.68,-0.55,0.27,1.55)',
    easeSpring: 'cubic-bezier(0.68,-0.6,0.27,1.7)',
    fast: '180ms',
    base: '420ms',
    slow: '760ms',
    stagger: 55,
    lift: '8px',
    scale: '1.045',
    blur: '0px',
    ambient: 'pulse',
    ambientSpeed: '9s',
    speed: 1.1,
  },
  {
    id: 'cinematic',
    name: 'Cinematic',
    note: 'Slow dolly-in, deep easing. Feels like a film title card.',
    enter: 'pb-zoom-in',
    ease: 'cubic-bezier(0.19,1,0.22,1)',
    easeSpring: 'cubic-bezier(0.19,1,0.22,1)',
    fast: '260ms',
    base: '620ms',
    slow: '1200ms',
    stagger: 90,
    lift: '5px',
    scale: '1.012',
    blur: '2px',
    ambient: 'drift',
    ambientSpeed: '34s',
    speed: 1.35,
  },
  {
    id: 'snap',
    name: 'Snap',
    note: 'Short and decisive. Built for people who click fast.',
    enter: 'pb-slide-up',
    ease: 'cubic-bezier(0.2,0,0,1)',
    easeSpring: 'cubic-bezier(0.2,0,0,1)',
    fast: '90ms',
    base: '180ms',
    slow: '320ms',
    stagger: 18,
    lift: '2px',
    scale: '1.005',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '12s',
    speed: 0.65,
  },
  {
    id: 'bounce',
    name: 'Bounce',
    note: 'Cards hop as they arrive. Impossible to be grumpy at.',
    enter: 'pb-drop',
    ease: 'cubic-bezier(0.5,1.6,0.5,1)',
    easeSpring: 'cubic-bezier(0.5,1.8,0.5,1)',
    fast: '170ms',
    base: '380ms',
    slow: '640ms',
    stagger: 50,
    lift: '10px',
    scale: '1.05',
    blur: '0px',
    ambient: 'pulse',
    ambientSpeed: '7s',
    speed: 1.05,
  },
  {
    id: 'drift',
    name: 'Drift',
    note: 'Elements float upward like they are underwater.',
    enter: 'pb-rise',
    ease: 'cubic-bezier(0.33,0.9,0.5,1)',
    easeSpring: 'cubic-bezier(0.33,1.2,0.5,1)',
    fast: '220ms',
    base: '520ms',
    slow: '1000ms',
    stagger: 70,
    lift: '4px',
    scale: '1.006',
    blur: '1px',
    ambient: 'drift',
    ambientSpeed: '20s',
    speed: 1.2,
  },
  {
    id: 'pulse',
    name: 'Pulse',
    note: 'A steady heartbeat in the background, calm in the foreground.',
    enter: 'pb-fade',
    ease: 'cubic-bezier(0.4,0,0.6,1)',
    easeSpring: 'cubic-bezier(0.4,0,0.6,1)',
    fast: '150ms',
    base: '300ms',
    slow: '560ms',
    stagger: 36,
    lift: '3px',
    scale: '1.008',
    blur: '0px',
    ambient: 'pulse',
    ambientSpeed: '5s',
    speed: 1,
  },
  {
    id: 'orbit',
    name: 'Orbit',
    note: 'Ambient shapes circle slowly while content stays crisp.',
    enter: 'pb-rise',
    ease: 'cubic-bezier(0.25,0.8,0.35,1)',
    easeSpring: 'cubic-bezier(0.25,1.1,0.35,1)',
    fast: '180ms',
    base: '360ms',
    slow: '720ms',
    stagger: 48,
    lift: '4px',
    scale: '1.01',
    blur: '0px',
    ambient: 'orbit',
    ambientSpeed: '30s',
    speed: 1.05,
  },
  {
    id: 'cascade',
    name: 'Cascade',
    note: 'Big per-item stagger — lists arrive like a wave.',
    enter: 'pb-rise',
    ease: 'cubic-bezier(0.22,1,0.36,1)',
    easeSpring: 'cubic-bezier(0.22,1.2,0.36,1)',
    fast: '160ms',
    base: '340ms',
    slow: '640ms',
    stagger: 110,
    lift: '4px',
    scale: '1.01',
    blur: '0px',
    ambient: 'float',
    ambientSpeed: '16s',
    speed: 1.1,
  },
  {
    id: 'typewriter',
    name: 'Typewriter',
    note: 'Headlines and panels type themselves in, character by character.',
    enter: 'pb-type',
    ease: 'steps(28,end)',
    easeSpring: 'cubic-bezier(0.4,0,0.2,1)',
    fast: '200ms',
    base: '420ms',
    slow: '700ms',
    stagger: 60,
    lift: '2px',
    scale: '1',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '20s',
    speed: 1,
  },
  {
    id: 'flip',
    name: 'Flip',
    note: 'Cards turn over like cue cards on a stage.',
    enter: 'pb-flip-in',
    ease: 'cubic-bezier(0.34,1.4,0.64,1)',
    easeSpring: 'cubic-bezier(0.34,1.5,0.64,1)',
    fast: '200ms',
    base: '440ms',
    slow: '760ms',
    stagger: 58,
    lift: '6px',
    scale: '1.02',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '18s',
    speed: 1.15,
  },
  {
    id: 'zoomfade',
    name: 'Zoom Fade',
    note: 'Content scales up from behind the page. Slide-deck energy.',
    enter: 'pb-zoom-out',
    ease: 'cubic-bezier(0.16,1,0.3,1)',
    easeSpring: 'cubic-bezier(0.16,1.2,0.3,1)',
    fast: '170ms',
    base: '380ms',
    slow: '700ms',
    stagger: 42,
    lift: '4px',
    scale: '1.015',
    blur: '1px',
    ambient: 'shimmer',
    ambientSpeed: '12s',
    speed: 1.05,
  },
  {
    id: 'slide',
    name: 'Slide Deck',
    note: 'Panels slide in from the side, exactly like a presentation.',
    enter: 'pb-slide-left',
    ease: 'cubic-bezier(0.22,1,0.36,1)',
    easeSpring: 'cubic-bezier(0.22,1.1,0.36,1)',
    fast: '160ms',
    base: '360ms',
    slow: '620ms',
    stagger: 44,
    lift: '3px',
    scale: '1',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '18s',
    speed: 1,
  },
  {
    id: 'quantum',
    name: 'Quantum',
    note: 'Everything resolves out of focus. Very modern, very calm.',
    enter: 'pb-blur-in',
    ease: 'cubic-bezier(0.16,1,0.3,1)',
    easeSpring: 'cubic-bezier(0.16,1,0.3,1)',
    fast: '220ms',
    base: '480ms',
    slow: '820ms',
    stagger: 52,
    lift: '4px',
    scale: '1.012',
    blur: '10px',
    ambient: 'shimmer',
    ambientSpeed: '16s',
    speed: 1.25,
  },
  {
    id: 'swirl',
    name: 'Swirl',
    note: 'A gentle rotation on arrival. Adds theatre without noise.',
    enter: 'pb-unfold',
    ease: 'cubic-bezier(0.34,1.3,0.64,1)',
    easeSpring: 'cubic-bezier(0.34,1.4,0.64,1)',
    fast: '190ms',
    base: '400ms',
    slow: '700ms',
    stagger: 50,
    lift: '5px',
    scale: '1.02',
    blur: '2px',
    ambient: 'orbit',
    ambientSpeed: '22s',
    speed: 1.1,
  },
  {
    id: 'ripple',
    name: 'Ripple',
    note: 'Content spreads outward from its own centre point.',
    enter: 'pb-ripple',
    ease: 'cubic-bezier(0.2,0.8,0.2,1)',
    easeSpring: 'cubic-bezier(0.2,1,0.2,1)',
    fast: '180ms',
    base: '400ms',
    slow: '760ms',
    stagger: 46,
    lift: '4px',
    scale: '1.01',
    blur: '1px',
    ambient: 'shimmer',
    ambientSpeed: '14s',
    speed: 1.1,
  },
  {
    id: 'spotlight',
    name: 'Spotlight',
    note: 'A light sweeps across new content as it appears.',
    enter: 'pb-spotlight',
    ease: 'cubic-bezier(0.19,1,0.22,1)',
    easeSpring: 'cubic-bezier(0.19,1,0.22,1)',
    fast: '200ms',
    base: '460ms',
    slow: '860ms',
    stagger: 64,
    lift: '4px',
    scale: '1.008',
    blur: '2px',
    ambient: 'shimmer',
    ambientSpeed: '10s',
    speed: 1.15,
  },
  {
    id: 'swift',
    name: 'Swift',
    note: 'Micro-interactions only — instant feedback, nothing decorative.',
    enter: 'pb-slide-up',
    ease: 'cubic-bezier(0,0,0.2,1)',
    easeSpring: 'cubic-bezier(0,0,0.2,1)',
    fast: '70ms',
    base: '140ms',
    slow: '240ms',
    stagger: 12,
    lift: '2px',
    scale: '1.004',
    blur: '0px',
    ambient: 'none',
    ambientSpeed: '10s',
    speed: 0.55,
  },
];

export const DEFAULT_MOTION = 'breeze';
