import type { ThemePreset } from './types';

/**
 * 24 designer presets — complete, coherent combinations of all five axes.
 * These are the "I just want it to look good" button.
 */
export const PRESETS: ThemePreset[] = [
  {
    id: 'midnight-keynote',
    name: 'Midnight Keynote',
    note: 'Deep aurora glass, big poster cards, elegant serif display.',
    color: 'aurora',
    motion: 'glide',
    layout: 'showcase',
    ui: 'glass',
    ux: 'elegant',
  },
  {
    id: 'sunday-paper',
    name: 'Sunday Paper',
    note: 'Porcelain white, magazine columns, real newspaper warmth.',
    color: 'porcelain',
    motion: 'calm',
    layout: 'editorial',
    ui: 'paper',
    ux: 'editorial',
  },
  {
    id: 'studio-clay',
    name: 'Studio Clay',
    note: 'Terracotta, puffy bento tiles, rounded friendly type.',
    color: 'terracotta',
    motion: 'spring',
    layout: 'bento',
    ui: 'clay',
    ux: 'rounded',
  },
  {
    id: 'deep-focus',
    name: 'Deep Focus',
    note: 'Monochrome, zero motion, one thing on screen at a time.',
    color: 'noir',
    motion: 'still',
    layout: 'zen',
    ui: 'minimal',
    ux: 'focusread',
  },
  {
    id: 'neon-deck',
    name: 'Neon Deck',
    note: 'Cyberpunk magenta, holographic tiles, condensed headlines.',
    color: 'neon',
    motion: 'quantum',
    layout: 'gallery',
    ui: 'holo',
    ux: 'condensed',
  },
  {
    id: 'forest-cabin',
    name: 'Forest Cabin',
    note: 'Canopy greens, masonry wall, book-serif reading.',
    color: 'canopy',
    motion: 'breeze',
    layout: 'masonry',
    ui: 'paper',
    ux: 'classic',
  },
  {
    id: 'blueprint-lab',
    name: 'Blueprint Lab',
    note: 'Technical blue, drafting grid, monospace everything.',
    color: 'pacific',
    motion: 'swift',
    layout: 'dashboard',
    ui: 'blueprint',
    ux: 'mono',
  },
  {
    id: 'sunset-stage',
    name: 'Sunset Stage',
    note: 'Dusk gradients, widescreen covers, cinematic arrivals.',
    color: 'sunset',
    motion: 'cinematic',
    layout: 'theatre',
    ui: 'gradient',
    ux: 'elegant',
  },
  {
    id: 'gallery-white',
    name: 'Gallery White',
    note: 'Maximum legibility, hard surfaces, sans default.',
    color: 'paper',
    motion: 'calm',
    layout: 'gallery',
    ui: 'solid',
    ux: 'humanist',
  },
  {
    id: 'brass-oak',
    name: 'Brass & Oak',
    note: 'Inkwell black, brass accents, framed document sheets.',
    color: 'inkwell',
    motion: 'glide',
    layout: 'dossier',
    ui: 'frame',
    ux: 'editorial',
  },
  {
    id: 'lagoon-flow',
    name: 'Lagoon Flow',
    note: 'Turquoise glass, drifting masonry, airy comfortable type.',
    color: 'lagoon',
    motion: 'drift',
    layout: 'masonry',
    ui: 'glass',
    ux: 'airy',
  },
  {
    id: 'terminal-craft',
    name: 'Terminal Craft',
    note: 'Abyss teal, phosphor edges, index-table density.',
    color: 'abyss',
    motion: 'snap',
    layout: 'table',
    ui: 'retro',
    ux: 'mono',
  },
  {
    id: 'sakura-notes',
    name: 'Sakura Notes',
    note: 'Blush pink, bouncing card stack, handwritten-adjacent type.',
    color: 'sakura',
    motion: 'bounce',
    layout: 'stack',
    ui: 'sticker',
    ux: 'notes',
  },
  {
    id: 'arctic-pro',
    name: 'Arctic Pro',
    note: 'Icy blue, split-view inbox, snappy professional chrome.',
    color: 'arctic',
    motion: 'swift',
    layout: 'split',
    ui: 'elevated',
    ux: 'grotesk',
  },
  {
    id: 'desert-manuscript',
    name: 'Desert Manuscript',
    note: 'Dune sand, single-column zen, quiet classic serif.',
    color: 'dune',
    motion: 'calm',
    layout: 'zen',
    ui: 'paper',
    ux: 'classic',
  },
  {
    id: 'violet-hour',
    name: 'Violet Hour',
    note: 'Ultraviolet, orbiting constellation tiles, wide-tracked caps.',
    color: 'ultraviolet',
    motion: 'orbit',
    layout: 'constellation',
    ui: 'holo',
    ux: 'wide',
  },
  {
    id: 'ledger-desk',
    name: 'Ledger Desk',
    note: 'Slate neutral, ruled rows, no nonsense, no motion.',
    color: 'slatepro',
    motion: 'still',
    layout: 'ledger',
    ui: 'flat',
    ux: 'compact',
  },
  {
    id: 'wine-cellar',
    name: 'Wine Cellar',
    note: 'Bordeaux darkroom, spotlight hero, slow cinematic fade.',
    color: 'bordeaux',
    motion: 'cinematic',
    layout: 'spotlight',
    ui: 'darkroom',
    ux: 'elegant',
  },
  {
    id: 'big-print',
    name: 'Big Print',
    note: 'Signal yellow on black, huge type, built for accessibility.',
    color: 'contrast',
    motion: 'still',
    layout: 'focus',
    ui: 'solid',
    ux: 'stage',
  },
  {
    id: 'mint-sprint',
    name: 'Mint Sprint',
    note: 'Fresh mint, dense dashboard, fastest interaction timing.',
    color: 'mintlab',
    motion: 'swift',
    layout: 'dashboard',
    ui: 'soft',
    ux: 'grotesk',
  },
  {
    id: 'cocoa-corner',
    name: 'Cocoa Corner',
    note: 'Espresso browns, clay carousel tiles, cosy note serif.',
    color: 'cocoa',
    motion: 'pulse',
    layout: 'carousel',
    ui: 'clay',
    ux: 'notes',
  },
  {
    id: 'swiss-modern',
    name: 'Swiss Modern',
    note: 'Hairline grid, hard angles, grotesk typography. Poster purity.',
    color: 'porcelain',
    motion: 'snap',
    layout: 'gallery',
    ui: 'swiss',
    ux: 'grotesk',
  },
  {
    id: 'lavender-writing',
    name: 'Lavender Writing',
    note: 'Misty violets, calm zen column, airy leading for drafting.',
    color: 'lavender',
    motion: 'breeze',
    layout: 'zen',
    ui: 'glass',
    ux: 'airy',
  },
  {
    id: 'sandstone-archive',
    name: 'Sandstone Archive',
    note: 'Warm stone, etched dossier sheets, archival serif.',
    color: 'sandstone',
    motion: 'calm',
    layout: 'dossier',
    ui: 'etch',
    ux: 'classic',
  },
];
