import type { ThemePreset } from './types';

/**
 * 24 complete combinations, named like editions rather than like software.
 * The first one is what a visitor sees on their very first visit.
 */
export const PRESETS: ThemePreset[] = [
  {
    id: 'opening-page',
    name: 'Opening Page',
    note: 'Sand, terracotta, pressed paper. Where everyone starts.',
    color: 'sand-terracotta',
    motion: 'steady',
    layout: 'reading-room',
    ui: 'paper',
    ux: 'newsreader',
  },
  {
    id: 'the-kiln',
    name: 'The Kiln',
    note: 'Hotter clay, olive shadow, by-hand timing.',
    color: 'kiln',
    motion: 'by-hand',
    layout: 'notice-board',
    ui: 'letterpress',
    ux: 'fraunces-set',
  },
  {
    id: 'sunday-reading',
    name: 'Sunday Reading',
    note: 'Vellum, wide columns, nothing due today.',
    color: 'vellum',
    motion: 'unhurried',
    layout: 'columns',
    ui: 'vellum-sheet',
    ux: 'source-serif',
  },
  {
    id: 'newsroom',
    name: 'Newsroom',
    note: 'Grey pulp, black ink, ruled tight. Deadline energy.',
    color: 'newsprint',
    motion: 'march',
    layout: 'news-sheet',
    ui: 'newsprint-sheet',
    ux: 'broadsheet-set',
  },
  {
    id: 'card-drawer',
    name: 'Card Drawer',
    note: 'Index cards and a pencil. The librarian’s combination.',
    color: 'archive-blue',
    motion: 'tap',
    layout: 'card-catalogue',
    ui: 'index-card',
    ux: 'spectral',
  },
  {
    id: 'night-reading',
    name: 'Night Reading',
    note: 'Blue-black ink, amber lamp. For after the house is quiet.',
    color: 'night-ink',
    motion: 'hush',
    layout: 'chapbook',
    ui: 'cloth-bound',
    ux: 'newsreader',
  },
  {
    id: 'chalk-talk',
    name: 'Chalk Talk',
    note: 'Slate green and chalk dust. Feels like being taught.',
    color: 'chalkboard',
    motion: 'settle',
    layout: 'broadside',
    ui: 'chalk',
    ux: 'large-print',
  },
  {
    id: 'carbon-copy',
    name: 'Carbon Copy',
    note: 'Duplicated grey sheets. Utilitarian and oddly handsome.',
    color: 'carbon',
    motion: 'step',
    layout: 'folder',
    ui: 'carbon-paper',
    ux: 'mono-archive',
  },
  {
    id: 'riso-print',
    name: 'Riso Print',
    note: 'Cornflower and tomato, printed a hair out of register.',
    color: 'risograph',
    motion: 'skip',
    layout: 'gallery-wall',
    ui: 'risograph-print',
    ux: 'condensed-set',
  },
  {
    id: 'workshop',
    name: 'Workshop',
    note: 'Ochre, linen, a bench and good light.',
    color: 'mustard',
    motion: 'nod',
    layout: 'workbench',
    ui: 'linen-cover',
    ux: 'inter-clean',
  },
  {
    id: 'olive-grove',
    name: 'Olive Grove',
    note: 'Green-gold, slow as a long lunch.',
    color: 'olive-press',
    motion: 'breath',
    layout: 'scrapbook',
    ui: 'pinned-note',
    ux: 'airy-set',
  },
  {
    id: 'fireside',
    name: 'Fireside',
    note: 'Embers, brown paper, a blanket.',
    color: 'ember-dark',
    motion: 'lantern',
    layout: 'stage',
    ui: 'ink-wash',
    ux: 'lora-classic',
  },
  {
    id: 'field-notes',
    name: 'Field Notes',
    note: 'Ruled paper and a pen that works. For writing, not reading.',
    color: 'linen',
    motion: 'quickstep',
    layout: 'chapbook',
    ui: 'ruled-paper',
    ux: 'marginalia',
  },
  {
    id: 'the-archive',
    name: 'The Archive',
    note: 'Sepia photographs and a date written on the back.',
    color: 'sepia',
    motion: 'glide',
    layout: 'almanac',
    ui: 'cloth-bound',
    ux: 'source-serif',
  },
  {
    id: 'indigo-desk',
    name: 'Indigo Desk',
    note: 'Cold indigo on cotton rag. Clear-headed and steady.',
    color: 'indigo-dye',
    motion: 'steady',
    layout: 'desk',
    ui: 'cardstock',
    ux: 'spectral',
  },
  {
    id: 'plum-correspondence',
    name: 'Plum Correspondence',
    note: 'Blackberry ink on cream. For letters you keep.',
    color: 'plum-ink',
    motion: 'drift',
    layout: 'stack-of-pages',
    ui: 'tape',
    ux: 'lora-classic',
  },
  {
    id: 'sea-glass',
    name: 'Sea Glass',
    note: 'Frosted green, wet sand, an early swim.',
    color: 'sea-glass',
    motion: 'tide',
    layout: 'display-case',
    ui: 'etched-glass',
    ux: 'quiet-set',
  },
  {
    id: 'brick-wall',
    name: 'Brick Wall',
    note: 'Crushed brick and lime. Solid, warm, immovable.',
    color: 'brick-dust',
    motion: 'settle',
    layout: 'bulletin',
    ui: 'stone',
    ux: 'newsreader',
  },
  {
    id: 'pine-workshop',
    name: 'Pine Workshop',
    note: 'Resin green and sawdust. Make something.',
    color: 'pine-wood',
    motion: 'page-turn',
    layout: 'rail',
    ui: 'woodblock',
    ux: 'inter-clean',
  },
  {
    id: 'dusk',
    name: 'Dusk',
    note: 'Violet light on a page, at the end of the day.',
    color: 'dusk-paper',
    motion: 'unhurried',
    layout: 'slideshow',
    ui: 'foil',
    ux: 'focus-set',
  },
  {
    id: 'ledger-book',
    name: 'Ledger Book',
    note: 'Hairlines, figures, and no decoration whatsoever.',
    color: 'slate-roof',
    motion: 'still',
    layout: 'ledger',
    ui: 'bare',
    ux: 'compact-set',
  },
  {
    id: 'black-and-cream',
    name: 'Black & Cream',
    note: 'The accessible edition. Maximum legibility, nothing in the way.',
    color: 'black-cream',
    motion: 'still',
    layout: 'reading-room',
    ui: 'paper',
    ux: 'high-contrast-set',
  },
  {
    id: 'signal-lamp',
    name: 'Signal Lamp',
    note: 'Amber on black. For bright rooms, projectors and low vision.',
    color: 'signal',
    motion: 'tap',
    layout: 'slideshow',
    ui: 'stamp',
    ux: 'stage-set',
  },
  {
    id: 'cocoa-corner',
    name: 'Cocoa Corner',
    note: 'Espresso and cream. A chair you sink into.',
    color: 'cocoa',
    motion: 'breath',
    layout: 'stage',
    ui: 'cloth-bound',
    ux: 'marginalia',
  },
];
