import type { ThemePreset } from './types';

/**
 * Fourteen complete combinations, curated like editions rather than picked
 * like software settings. The first one is what a visitor sees on their
 * very first visit; every preset below resolves against real options on
 * all five axes (checked by the smoke test).
 */
export const PRESETS: ThemePreset[] = [
  {
    id: 'opening-page',
    name: 'Opening Page',
    note: 'Sand, terracotta, pressed paper. Where everyone starts.',
    color: 'sand-terracotta',
    motion: 'steady',
    layout: 'reading-room',
    ui: 'paper',
    ux: 'newsreader',
  },
  {
    id: 'the-kiln',
    name: 'The Kiln',
    note: 'Hotter clay, olive shadow, by-hand timing.',
    color: 'kiln',
    motion: 'by-hand',
    layout: 'notice-board',
    ui: 'letterpress',
    ux: 'fraunces-set',
  },
  {
    id: 'newsroom',
    name: 'Newsroom',
    note: 'Ink on newsprint at walking pace. Facts first.',
    color: 'newsprint',
    motion: 'quickstep',
    layout: 'news-sheet',
    ui: 'newsprint-sheet',
    ux: 'broadsheet-set',
  },
  {
    id: 'night-reading',
    name: 'Night Reading',
    note: 'A lamp, a blanket and nothing else lit in the house.',
    color: 'night-ink',
    motion: 'hush',
    layout: 'reading-room',
    ui: 'vellum-sheet',
    ux: 'source-serif',
  },
  {
    id: 'chalk-talk',
    name: 'Chalk Talk',
    note: 'The blackboard after a good lecture — dust on the tray.',
    color: 'chalkboard',
    motion: 'march',
    layout: 'slideshow',
    ui: 'chalk',
    ux: 'stage-set',
  },
  {
    id: 'riso-print',
    name: 'Riso Print',
    note: 'Two drums, misregistered on purpose, quilted into a zine.',
    color: 'risograph',
    motion: 'skip',
    layout: 'patchwork',
    ui: 'risograph-print',
    ux: 'compact-set',
  },
  {
    id: 'signal-lamp',
    name: 'Signal Lamp',
    note: 'Amber on black. For bright rooms, projectors and low vision.',
    color: 'signal',
    motion: 'tap',
    layout: 'slideshow',
    ui: 'stamp',
    ux: 'stage-set',
  },
  {
    id: 'cocoa-corner',
    name: 'Cocoa Corner',
    note: 'Espresso and cream. A chair you sink into.',
    color: 'cocoa',
    motion: 'breath',
    layout: 'stage',
    ui: 'cloth-bound',
    ux: 'marginalia',
  },
  {
    id: 'jade-teahouse',
    name: 'Jade Teahouse',
    note: 'Celadon porcelain, a rust seal, and the tour taken slowly.',
    color: 'jade-garden',
    motion: 'sway',
    layout: 'guided-tour',
    ui: 'linen-cover',
    ux: 'recital-set',
  },
  {
    id: 'sakura-letter',
    name: 'Sakura Letter',
    note: 'Blush stationery under glass, cards falling like petals.',
    color: 'sakura',
    motion: 'cascade',
    layout: 'gallery-wall',
    ui: 'porcelain',
    ux: 'gallery-set',
  },
  {
    id: 'deep-sea-keynote',
    name: 'Deep Sea Keynote',
    note: 'Abyssal blue, a warm beacon, one headline in the atrium.',
    color: 'deep-sea',
    motion: 'curtain',
    layout: 'the-atrium',
    ui: 'hologram',
    ux: 'deck-set',
  },
  {
    id: 'aurora-forum',
    name: 'Aurora Forum',
    note: 'Midnight violet setlist, mint signal, a deck built for the back row.',
    color: 'aurora',
    motion: 'tide',
    layout: 'setlist',
    ui: 'hologram',
    ux: 'planner-set',
  },
  {
    id: 'foundry',
    name: 'Foundry',
    note: 'Carbon stock and bronze plate. Heavy machinery, well oiled.',
    color: 'carbon',
    motion: 'quickstep',
    layout: 'workbench',
    ui: 'bronze-plate',
    ux: 'deck-set',
  },
  {
    id: 'kraft-fair',
    name: 'Kraft Fair',
    note: 'Stamped brown wrap and typewriter ribbon at the maker stall.',
    color: 'brick-dust',
    motion: 'page-turn',
    layout: 'bulletin',
    ui: 'kraft',
    ux: 'typewriter-set',
  },
];
