import type { UxTheme } from './types';

const NEWSREADER = "'Newsreader', 'Iowan Old Style', Georgia, serif";
const SPECTRAL = "Spectral, 'Iowan Old Style', Georgia, serif";
const FRAUNCES = "Fraunces, 'Playfair Display', Georgia, serif";
const SOURCE_SERIF = "'Source Serif 4', 'Iowan Old Style', Georgia, serif";
const LORA = 'Lora, Georgia, serif';
const INTER = "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
const GROTESK = "'Space Grotesk', Inter, -apple-system, 'Segoe UI', Roboto, sans-serif";
const MONO = "'JetBrains Mono', ui-monospace, 'SFMono-Regular', Consolas, monospace";
const HAND = "'Caveat', 'Bradley Hand', 'Segoe Print', cursive";
const SYSTEM =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Noto Sans Devanagari', 'Nirmala UI', 'Noto Sans', sans-serif";

/**
 * 22 typography systems. Each pairing was chosen the way a book designer
 * chooses one: a voice for the headline, a voice for the sentence, and a
 * measure you can actually read a whole page of.
 */
export const UX_THEMES: UxTheme[] = [
  {
    id: 'newsreader',
    name: 'Newsreader',
    note: 'The house setting: a reading serif with Fraunces for the titles.',
    fontBody: NEWSREADER,
    fontDisplay: FRAUNCES,
    fontMono: MONO,
    scale: 1.02,
    tracking: '0em',
    leading: 1.72,
    weightBody: 400,
    weightDisplay: 600,
    measure: 66,
    para: '1.15em',
    radiusScale: 1,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'spectral',
    name: 'Spectral',
    note: 'Screen-native serif, slightly condensed. Reads well on phones.',
    fontBody: SPECTRAL,
    fontDisplay: SPECTRAL,
    fontMono: MONO,
    scale: 1,
    tracking: '0em',
    leading: 1.68,
    weightBody: 400,
    weightDisplay: 700,
    measure: 68,
    para: '1.12em',
    radiusScale: 0.9,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'fraunces-set',
    name: 'Soft Serif',
    note: 'Fraunces throughout, with its soft optical sizing turned up.',
    fontBody: FRAUNCES,
    fontDisplay: FRAUNCES,
    fontMono: MONO,
    scale: 1.02,
    tracking: '-0.004em',
    leading: 1.75,
    weightBody: 400,
    weightDisplay: 600,
    measure: 64,
    para: '1.2em',
    radiusScale: 1.1,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'inter-clean',
    name: 'Plain Sans',
    note: 'Inter for everything. Clean, neutral, all business.',
    fontBody: INTER,
    fontDisplay: INTER,
    fontMono: MONO,
    scale: 1,
    tracking: '0em',
    leading: 1.62,
    weightBody: 400,
    weightDisplay: 650,
    measure: 70,
    para: '1.05em',
    radiusScale: 1,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'source-serif',
    name: 'Source Serif',
    note: 'A bookish workhorse. Comfortable for very long reading.',
    fontBody: SOURCE_SERIF,
    fontDisplay: SOURCE_SERIF,
    fontMono: MONO,
    scale: 1.02,
    tracking: '0em',
    leading: 1.76,
    weightBody: 400,
    weightDisplay: 700,
    measure: 63,
    para: '1.25em',
    radiusScale: 0.7,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'lora-classic',
    name: 'Lora Classic',
    note: 'Brushed curves, magazine warmth. Good for ceremonial pieces.',
    fontBody: LORA,
    fontDisplay: LORA,
    fontMono: MONO,
    scale: 0.98,
    tracking: '0.002em',
    leading: 1.7,
    weightBody: 400,
    weightDisplay: 700,
    measure: 68,
    para: '1.1em',
    radiusScale: 0.8,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'mono-archive',
    name: 'Archive Mono',
    note: 'Everything typeset like a catalogue entry from 1974.',
    fontBody: MONO,
    fontDisplay: MONO,
    fontMono: MONO,
    scale: 0.94,
    tracking: '-0.008em',
    leading: 1.72,
    weightBody: 400,
    weightDisplay: 600,
    measure: 74,
    para: '1em',
    radiusScale: 0.4,
    caps: true,
    focus: '0 0 0 3px',
  },
  {
    id: 'marginalia',
    name: 'Marginalia',
    note: 'Serif body with handwritten headings, like notes in a margin.',
    fontBody: NEWSREADER,
    fontDisplay: HAND,
    fontMono: MONO,
    scale: 1.04,
    tracking: '0em',
    leading: 1.75,
    weightBody: 400,
    weightDisplay: 600,
    measure: 64,
    para: '1.2em',
    radiusScale: 1,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'large-print',
    name: 'Large Print',
    note: 'Generous 18px base. For tired eyes and the back of the room.',
    fontBody: INTER,
    fontDisplay: FRAUNCES,
    fontMono: MONO,
    scale: 1.18,
    tracking: '0.004em',
    leading: 1.7,
    weightBody: 400,
    weightDisplay: 700,
    measure: 58,
    para: '1.2em',
    radiusScale: 1.1,
    caps: false,
    focus: '0 0 0 4px',
  },
  {
    id: 'compact-set',
    name: 'Compact Set',
    note: 'Tight scale, long lines. Fit more on the page, stay legible.',
    fontBody: INTER,
    fontDisplay: GROTESK,
    fontMono: MONO,
    scale: 0.9,
    tracking: '-0.004em',
    leading: 1.5,
    weightBody: 400,
    weightDisplay: 650,
    measure: 78,
    para: '0.95em',
    radiusScale: 0.8,
    caps: false,
    focus: '0 0 0 2px',
  },
  {
    id: 'airy-set',
    name: 'Airy Set',
    note: 'Wide leading and generous paragraph breaks. Room to breathe.',
    fontBody: SOURCE_SERIF,
    fontDisplay: FRAUNCES,
    fontMono: MONO,
    scale: 1.06,
    tracking: '0.002em',
    leading: 1.92,
    weightBody: 400,
    weightDisplay: 600,
    measure: 60,
    para: '1.5em',
    radiusScale: 1.2,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'dyslexia-set',
    name: 'Easy Read',
    note: 'Heavier weight, extra spacing, no italics. Widely easier to read.',
    fontBody: INTER,
    fontDisplay: INTER,
    fontMono: MONO,
    scale: 1.08,
    tracking: '0.02em',
    leading: 1.95,
    weightBody: 500,
    weightDisplay: 700,
    measure: 54,
    para: '1.6em',
    radiusScale: 1,
    caps: false,
    focus: '0 0 0 4px',
  },
  {
    id: 'high-contrast-set',
    name: 'Strong Contrast',
    note: 'Maximum weight separation and the shortest possible measure.',
    fontBody: INTER,
    fontDisplay: GROTESK,
    fontMono: MONO,
    scale: 1.1,
    tracking: '0.006em',
    leading: 1.75,
    weightBody: 500,
    weightDisplay: 700,
    measure: 52,
    para: '1.35em',
    radiusScale: 0.9,
    caps: false,
    focus: '0 0 0 4px',
  },
  {
    id: 'condensed-set',
    name: 'Condensed',
    note: 'Narrow headlines, efficient body. Discipline for long documents.',
    fontBody: INTER,
    fontDisplay: GROTESK,
    fontMono: MONO,
    scale: 0.98,
    tracking: '-0.02em',
    leading: 1.46,
    weightBody: 400,
    weightDisplay: 700,
    measure: 74,
    para: '0.95em',
    radiusScale: 0.7,
    caps: true,
    focus: '0 0 0 2px',
  },
  {
    id: 'wide-track-set',
    name: 'Wide Tracked',
    note: 'Letter-spaced small caps. Architectural and unhurried.',
    fontBody: INTER,
    fontDisplay: INTER,
    fontMono: MONO,
    scale: 1,
    tracking: '0.05em',
    leading: 1.78,
    weightBody: 400,
    weightDisplay: 600,
    measure: 62,
    para: '1.25em',
    radiusScale: 0.9,
    caps: true,
    focus: '0 0 0 3px',
  },
  {
    id: 'typewriter-set',
    name: 'Typewriter',
    note: 'Draft letter set on a machine. Charm and clatter.',
    fontBody: MONO,
    fontDisplay: LORA,
    fontMono: MONO,
    scale: 0.98,
    tracking: '0.004em',
    leading: 1.8,
    weightBody: 400,
    weightDisplay: 700,
    measure: 70,
    para: '1.15em',
    radiusScale: 0.5,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'broadsheet-set',
    name: 'Broadsheet',
    note: 'Newspaper columns with a justified rag and tight leading.',
    fontBody: LORA,
    fontDisplay: LORA,
    fontMono: MONO,
    scale: 0.98,
    tracking: '0em',
    leading: 1.6,
    weightBody: 400,
    weightDisplay: 700,
    measure: 72,
    para: '1.05em',
    radiusScale: 0.35,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'quiet-set',
    name: 'Quiet Set',
    note: 'Muted weights, narrow measure, quiet hierarchy. Calm by design.',
    fontBody: INTER,
    fontDisplay: INTER,
    fontMono: MONO,
    scale: 1,
    tracking: '0.008em',
    leading: 1.88,
    weightBody: 400,
    weightDisplay: 500,
    measure: 56,
    para: '1.4em',
    radiusScale: 1,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'focus-set',
    name: 'Single Line',
    note: 'One thought at a time: very narrow, very strong paragraph gaps.',
    fontBody: SOURCE_SERIF,
    fontDisplay: INTER,
    fontMono: MONO,
    scale: 1.12,
    tracking: '0em',
    leading: 1.82,
    weightBody: 400,
    weightDisplay: 600,
    measure: 46,
    para: '1.7em',
    radiusScale: 1,
    caps: false,
    focus: '0 0 0 4px',
  },
  {
    id: 'stage-set',
    name: 'Stage Display',
    note: 'Oversized type, tuned for reading from across a room.',
    fontBody: GROTESK,
    fontDisplay: GROTESK,
    fontMono: MONO,
    scale: 1.3,
    tracking: '-0.01em',
    leading: 1.55,
    weightBody: 500,
    weightDisplay: 700,
    measure: 44,
    para: '1.1em',
    radiusScale: 1.1,
    caps: false,
    focus: '0 0 0 4px',
  },
  {
    id: 'handwritten-set',
    name: 'Handwritten',
    note: 'A real hand for short notes. Use it sparingly, like a margin.',
    fontBody: HAND,
    fontDisplay: HAND,
    fontMono: MONO,
    scale: 1.16,
    tracking: '0.01em',
    leading: 1.5,
    weightBody: 400,
    weightDisplay: 600,
    measure: 60,
    para: '1em',
    radiusScale: 1.3,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'global-scripts',
    name: 'Global Scripts',
    note: 'System-first stack with Devanagari and CJK fallbacks. Multilingual.',
    fontBody: SYSTEM,
    fontDisplay: SYSTEM,
    fontMono: MONO,
    scale: 1.02,
    tracking: '0em',
    leading: 1.8,
    weightBody: 400,
    weightDisplay: 650,
    measure: 64,
    para: '1.2em',
    radiusScale: 1,
    caps: false,
    focus: '0 0 0 3px',
  },
];

export const DEFAULT_UX = 'newsreader';
