import type { UxTheme } from './types';

const SANS = "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Noto Sans', sans-serif";
const GROTESK = "'Space Grotesk', Inter, -apple-system, 'Segoe UI', Roboto, sans-serif";
const SERIF = "'Source Serif 4', 'Iowan Old Style', Georgia, 'Times New Roman', serif";
const LORA = "Lora, Georgia, 'Times New Roman', serif";
const FRAUNCES = "Fraunces, 'Playfair Display', Georgia, serif";
const MONO = "'JetBrains Mono', 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace";
const ROUNDED =
  "Inter, ui-rounded, 'SF Pro Rounded', 'Segoe UI Variable', 'Nunito', 'Noto Sans', sans-serif";
const SYSTEM =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Noto Sans Devanagari', 'Nirmala UI', 'Noto Sans', sans-serif";
const HUMANIST =
  "Inter, 'Segoe UI', 'Helvetica Neue', Arial, 'Noto Sans', sans-serif";

/**
 * 22 typography & reading experiences. These decide how words actually feel:
 * family pairing, scale, measure, leading and paragraph rhythm.
 */
export const UX_THEMES: UxTheme[] = [
  {
    id: 'editorial',
    name: 'Editorial Serif',
    note: 'Fraunces headlines over a serif body. Sunday-longform energy.',
    fontBody: SERIF,
    fontDisplay: FRAUNCES,
    fontMono: MONO,
    scale: 1.04,
    tracking: '-0.006em',
    leading: 1.72,
    weightBody: 400,
    weightDisplay: 700,
    measure: 64,
    para: '1.15em',
    radiusScale: 0.95,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'grotesk',
    name: 'Modern Grotesk',
    note: 'Space Grotesk everywhere. Sharp, confident, product-native.',
    fontBody: GROTESK,
    fontDisplay: GROTESK,
    fontMono: MONO,
    scale: 1,
    tracking: '-0.012em',
    leading: 1.6,
    weightBody: 400,
    weightDisplay: 700,
    measure: 66,
    para: '1.05em',
    radiusScale: 1,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'humanist',
    name: 'Humanist Sans',
    note: 'Inter at a comfortable size. The reliable all-rounder.',
    fontBody: HUMANIST,
    fontDisplay: SANS,
    fontMono: MONO,
    scale: 1,
    tracking: '0em',
    leading: 1.65,
    weightBody: 400,
    weightDisplay: 650,
    measure: 68,
    para: '1.05em',
    radiusScale: 1,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'mono',
    name: 'Mono Tech',
    note: 'Everything in a technical monospace. For engineers and poets.',
    fontBody: MONO,
    fontDisplay: MONO,
    fontMono: MONO,
    scale: 0.95,
    tracking: '-0.01em',
    leading: 1.7,
    weightBody: 400,
    weightDisplay: 600,
    measure: 72,
    para: '1em',
    radiusScale: 0.6,
    caps: true,
    focus: '0 0 0 3px',
  },
  {
    id: 'large',
    name: 'Large Print',
    note: 'Generous 18px base. Made for tired eyes and bright stages.',
    fontBody: SANS,
    fontDisplay: SANS,
    fontMono: MONO,
    scale: 1.18,
    tracking: '0.004em',
    leading: 1.7,
    weightBody: 400,
    weightDisplay: 700,
    measure: 58,
    para: '1.2em',
    radiusScale: 1.1,
    caps: false,
    focus: '0 0 0 4px',
  },
  {
    id: 'compact',
    name: 'Compact Pro',
    note: 'Tight scale and short lines. Fit more on screen, stay legible.',
    fontBody: SANS,
    fontDisplay: GROTESK,
    fontMono: MONO,
    scale: 0.9,
    tracking: '-0.004em',
    leading: 1.5,
    weightBody: 400,
    weightDisplay: 650,
    measure: 78,
    para: '0.95em',
    radiusScale: 0.8,
    caps: false,
    focus: '0 0 0 2px',
  },
  {
    id: 'airy',
    name: 'Airy Calm',
    note: 'Wide leading and long paragraph breaks. Room to breathe.',
    fontBody: SANS,
    fontDisplay: FRAUNCES,
    fontMono: MONO,
    scale: 1.06,
    tracking: '0.002em',
    leading: 1.9,
    weightBody: 400,
    weightDisplay: 600,
    measure: 60,
    para: '1.5em',
    radiusScale: 1.2,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'dyslexic',
    name: 'Dyslexia Friendly',
    note: 'Heavier weight, extra spacing, no italics, wide tracking.',
    fontBody: SANS,
    fontDisplay: SANS,
    fontMono: MONO,
    scale: 1.08,
    tracking: '0.02em',
    leading: 1.95,
    weightBody: 500,
    weightDisplay: 700,
    measure: 54,
    para: '1.6em',
    radiusScale: 1,
    caps: false,
    focus: '0 0 0 4px',
  },
  {
    id: 'contrast',
    name: 'High Contrast Type',
    note: 'Maximum weight separation and the shortest possible measure.',
    fontBody: SANS,
    fontDisplay: GROTESK,
    fontMono: MONO,
    scale: 1.1,
    tracking: '0.006em',
    leading: 1.75,
    weightBody: 500,
    weightDisplay: 700,
    measure: 52,
    para: '1.35em',
    radiusScale: 0.9,
    caps: false,
    focus: '0 0 0 4px',
  },
  {
    id: 'condensed',
    name: 'Condensed Deck',
    note: 'Narrow headlines, efficient body — deck-copy discipline.',
    fontBody: SANS,
    fontDisplay: GROTESK,
    fontMono: MONO,
    scale: 0.98,
    tracking: '-0.02em',
    leading: 1.45,
    weightBody: 400,
    weightDisplay: 700,
    measure: 74,
    para: '0.95em',
    radiusScale: 0.7,
    caps: true,
    focus: '0 0 0 2px',
  },
  {
    id: 'wide',
    name: 'Wide Track',
    note: 'Letter-spaced small caps headings. Architectural and calm.',
    fontBody: HUMANIST,
    fontDisplay: SANS,
    fontMono: MONO,
    scale: 1,
    tracking: '0.06em',
    leading: 1.75,
    weightBody: 400,
    weightDisplay: 600,
    measure: 62,
    para: '1.25em',
    radiusScale: 0.9,
    caps: true,
    focus: '0 0 0 3px',
  },
  {
    id: 'typewriter',
    name: 'Typewriter',
    note: 'Monospace body with Lora accents. Draft-letter charm.',
    fontBody: MONO,
    fontDisplay: LORA,
    fontMono: MONO,
    scale: 0.98,
    tracking: '0.004em',
    leading: 1.78,
    weightBody: 400,
    weightDisplay: 700,
    measure: 70,
    para: '1.15em',
    radiusScale: 0.5,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'brutalist',
    name: 'Brutalist Display',
    note: 'Huge squared headlines, tiny body copy. Poster behaviour.',
    fontBody: SANS,
    fontDisplay: GROTESK,
    fontMono: MONO,
    scale: 1.05,
    tracking: '-0.03em',
    leading: 1.4,
    weightBody: 400,
    weightDisplay: 700,
    measure: 76,
    para: '0.9em',
    radiusScale: 0.3,
    caps: true,
    focus: '0 0 0 3px',
  },
  {
    id: 'elegant',
    name: 'Elegant Contrast',
    note: 'Fraunces display against light Inter. Fine-dining typography.',
    fontBody: SANS,
    fontDisplay: FRAUNCES,
    fontMono: MONO,
    scale: 1.02,
    tracking: '-0.008em',
    leading: 1.68,
    weightBody: 400,
    weightDisplay: 600,
    measure: 64,
    para: '1.1em',
    radiusScale: 1.05,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'rounded',
    name: 'Rounded Friendly',
    note: 'Soft geometric sans with rounded corners. Never intimidating.',
    fontBody: ROUNDED,
    fontDisplay: ROUNDED,
    fontMono: MONO,
    scale: 1.02,
    tracking: '0em',
    leading: 1.7,
    weightBody: 400,
    weightDisplay: 700,
    measure: 64,
    para: '1.1em',
    radiusScale: 1.5,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'newsprint',
    name: 'Newsprint',
    note: 'Lora columns with justified rag, like a printed broadsheet.',
    fontBody: LORA,
    fontDisplay: LORA,
    fontMono: MONO,
    scale: 0.98,
    tracking: '0em',
    leading: 1.62,
    weightBody: 400,
    weightDisplay: 700,
    measure: 70,
    para: '1.05em',
    radiusScale: 0.35,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'lowstim',
    name: 'Low Stimulation',
    note: 'Muted weights, narrow measure, quiet hierarchy. Calm by design.',
    fontBody: HUMANIST,
    fontDisplay: SANS,
    fontMono: MONO,
    scale: 1,
    tracking: '0.008em',
    leading: 1.85,
    weightBody: 400,
    weightDisplay: 500,
    measure: 56,
    para: '1.4em',
    radiusScale: 1,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'focusread',
    name: 'Focus Reading',
    note: 'One sentence at a time: narrow measure, strong paragraph gaps.',
    fontBody: SERIF,
    fontDisplay: SANS,
    fontMono: MONO,
    scale: 1.12,
    tracking: '0em',
    leading: 1.8,
    weightBody: 400,
    weightDisplay: 600,
    measure: 46,
    para: '1.7em',
    radiusScale: 1,
    caps: false,
    focus: '0 0 0 4px',
  },
  {
    id: 'stage',
    name: 'Stage Display',
    note: 'Oversized type tuned for reading from the back of a room.',
    fontBody: GROTESK,
    fontDisplay: GROTESK,
    fontMono: MONO,
    scale: 1.3,
    tracking: '-0.01em',
    leading: 1.55,
    weightBody: 500,
    weightDisplay: 700,
    measure: 44,
    para: '1.1em',
    radiusScale: 1.1,
    caps: false,
    focus: '0 0 0 4px',
  },
  {
    id: 'notes',
    name: 'Note Taker',
    note: 'Handwritten-adjacent serif at note size. Studio scratchpad.',
    fontBody: LORA,
    fontDisplay: FRAUNCES,
    fontMono: MONO,
    scale: 0.96,
    tracking: '0.002em',
    leading: 1.72,
    weightBody: 400,
    weightDisplay: 700,
    measure: 68,
    para: '1.1em',
    radiusScale: 0.8,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'classic',
    name: 'Classic Book',
    note: 'Source Serif throughout. The feeling of a bound book.',
    fontBody: SERIF,
    fontDisplay: SERIF,
    fontMono: MONO,
    scale: 1.02,
    tracking: '0em',
    leading: 1.75,
    weightBody: 400,
    weightDisplay: 700,
    measure: 62,
    para: '1.25em',
    radiusScale: 0.6,
    caps: false,
    focus: '0 0 0 3px',
  },
  {
    id: 'global',
    name: 'Global Scripts',
    note: 'System-first stack with Devanagari and CJK fallbacks. Multilingual.',
    fontBody: SYSTEM,
    fontDisplay: SYSTEM,
    fontMono: MONO,
    scale: 1.02,
    tracking: '0em',
    leading: 1.8,
    weightBody: 400,
    weightDisplay: 650,
    measure: 64,
    para: '1.2em',
    radiusScale: 1,
    caps: false,
    focus: '0 0 0 3px',
  },
];

export const DEFAULT_UX = 'humanist';
